import { describe, expect, it } from 'vitest';

import packageJson from '../../package.json';

/**
 * **The catalog is `colleges.md` and nothing else, and no runner may reintroduce another one.**
 *
 * This test used to guard a weaker property. Its original job (plan P1-3, guarding P1-0) was to
 * keep the superseded catalog seeds *out of the `db:seed` chain* while deliberately keeping them
 * on disk behind their own local-only runners — 0002, the ten-career Manila demo fixture, and
 * 0004, the nationwide catalog of 20 institutions from Diliman to Iligan. The reasoning was that
 * reproducing pre-audit behaviour locally is a real need and an unchained script is harmless.
 *
 * It is no longer harmless, because the catalog is now scoped to one province. Seeds 0002 and 0004
 * between them seed Ateneo, La Salle, UST, UP Diliman, Silliman, USC, CIT-U and a dozen more, and
 * neither `colleges.name` nor `careers.title` carries a unique index — so `INSERT OR IGNORE` has
 * nothing to collide on and running either one *on top of* 0005 does not replace the Bohol catalog,
 * it adds a national one to it. The student-visible result is a recommendations screen offering
 * programmes in Manila.
 *
 * So both files were **deleted**, along with their `db:seed:catalog` and `db:seed:catalog:full`
 * runners, and this test now asserts the stronger invariant: `seeds/` contains exactly one catalog,
 * and every seed runner in `package.json` points at it. Git history holds the deleted seeds if a
 * wider catalog is ever wanted again.
 *
 * The reason this is worth a test rather than a comment: the defect is a *shell string* in
 * `package.json`. No type-checks it, no linter reads it, and the only symptom is a college card
 * from the wrong island on a screen nobody re-checks after seeding. `db:seed` is also the command
 * a new machine, a fresh CI runner and the production runbook all run, so a regression here reaches
 * every environment at once — and it is one `&&` away at all times.
 *
 * The chain is **resolved transitively rather than string-matched**, so it keeps holding if the
 * scripts are renamed.
 */

const scripts: Record<string, string> = packageJson.scripts;

/**
 * `import.meta.glob` is a Vite build-time transform, not a runtime API, so it has no type here:
 * `tsconfig.json` lists only `@cloudflare/workers-types` and the pool's types, and adding
 * `vite/client` to pick this up would put DOM globals in scope for `src/` too — where they do not
 * exist. One narrow declaration is cheaper than that, and narrower: only the keys are ever used.
 */
declare global {
  interface ImportMeta {
    glob(pattern: string, options?: { query?: string }): Record<string, unknown>;
  }
}

/**
 * The contents of `seeds/` as filenames.
 *
 * `import.meta.glob` rather than `readdirSync`: this suite runs inside workerd, where `node:fs`
 * exists as a stub whose `readdirSync` rejects a plain path ("File path must be a file: URL") and
 * which could not see the developer's filesystem regardless. The glob is resolved by Vite at
 * build time, on the real directory, and arrives in the worker as a plain object — which is
 * exactly the compile-time-on-disk / run-time-in-worker split this assertion needs.
 */
const seedFilesOnDisk = (): string[] =>
  Object.keys(import.meta.glob('../../seeds/*.sql', { query: '?raw' }))
    .map((path) => path.slice(path.lastIndexOf('/') + 1))
    .sort();

/** The one catalog seed. Generated by `scripts/build-region7-seed.mjs` from `colleges.md`. */
const CATALOG_SEED = '0005_region7_catalog_reset.sql';

/** Every `seeds/*.sql` file reached by running `npm run <name>`, in execution order. */
function resolveSeedFiles(name: string, seen: string[] = []): string[] {
  const command = scripts[name];

  // `throw` rather than `expect(...).toBeDefined()`: this runs inside a recursive walk, and an
  // assertion that does not narrow the type leaves the next line reading `command as string` —
  // a cast that would happily produce "undefined".split() if the guard were ever removed.
  if (command === undefined) {
    throw new Error(
      `package.json has no "${name}" script (chain: ${[...seen, name].join(' → ')})`,
    );
  }

  expect(seen, `"${name}" is chained into itself — npm would recurse forever`).not.toContain(
    name,
  );

  const files: string[] = [];

  // `&&`-separated segments, in order: `npm run a && npm run b` runs a then b.
  for (const segment of command.split('&&')) {
    const chained = /\bnpm\s+run\s+([\w:.-]+)/.exec(segment);

    if (chained?.[1] !== undefined) {
      files.push(...resolveSeedFiles(chained[1], [...seen, name]));
      continue;
    }

    const seedFile = /--file=\.\/seeds\/([\w.-]+\.sql)/.exec(segment);

    if (seedFile?.[1] !== undefined) {
      files.push(seedFile[1]);
    }
  }

  return files;
}

/** Every `--file=./seeds/*.sql` target across every script, deduplicated. */
function allSeedTargets(): string[] {
  const targets = new Set<string>();

  for (const command of Object.values(scripts)) {
    for (const match of command.matchAll(/--file=\.\/seeds\/([\w.-]+\.sql)/g)) {
      if (match[1] !== undefined) targets.add(match[1]);
    }
  }

  return [...targets].sort();
}

describe('seed chain — one catalog, and it is Bohol', () => {
  it('runs staff → catalog → ai-policy', () => {
    expect(resolveSeedFiles('db:seed')).toEqual([
      '0001_staff_accounts.sql',
      CATALOG_SEED,
      '0003_ai_policy.sql',
    ]);
  });

  it('applies the staff seed before the catalog', () => {
    // 0001 creates the seeded staff accounts every later fixture and the runbook's step 4 assume.
    const order = resolveSeedFiles('db:seed');

    expect(order.indexOf('0001_staff_accounts.sql')).toBe(0);
  });

  it('keeps exactly one catalog seed on disk', () => {
    // The deleted files are the assertion. `0002_academic_catalog.sql` and
    // `0004_academic_catalog_expansion.sql` seeded institutions outside Bohol; restoring either
    // file — even without a runner — is the first half of putting them back in a database, and
    // this is where that gets noticed.
    expect(seedFilesOnDisk()).toEqual([
      '0001_staff_accounts.sql',
      '0003_ai_policy.sql',
      CATALOG_SEED,
    ]);
  });

  it('points every seed runner at a seed that exists', () => {
    // A runner naming a deleted file fails at the shell with an unhelpful error, and only when
    // somebody runs it — which for the `:production` runners is the worst possible moment.
    const onDisk = new Set(seedFilesOnDisk());

    expect(allSeedTargets().filter((target) => !onDisk.has(target))).toEqual([]);
  });

  it('exposes no runner that seeds a catalog other than the Bohol one', () => {
    // Covers `--local` as well as `--remote`. The original version of this test only guarded
    // deployed databases, on the reasoning that a local database is disposable — but a developer
    // reading "25 colleges" locally and shipping against that assumption is how P1-0 happened.
    const catalogRunners = Object.entries(scripts)
      .filter(([name]) => name.startsWith('db:seed'))
      .filter(([, command]) => /--file=\.\/seeds\/000[245]_/.test(command))
      .map(([name, command]) => ({
        name,
        seed: /--file=\.\/seeds\/([\w.-]+\.sql)/.exec(command)?.[1],
      }))
      .filter(({ seed }) => seed !== CATALOG_SEED);

    expect(catalogRunners).toEqual([]);
  });
});
