import JSZip from 'jszip';
import { describe, expect, it } from 'vitest';

import { extractText, ExtractionError, MAX_EXTRACTED_TEXT_CHARS } from './extractText';

/**
 * **This file runs in real Chrome, not jsdom** — see the `browser` project in `vite.config.ts`.
 *
 * It used to carry a `vi.mock` re-pointing the worker's `?url` at a path on disk, because in Node
 * that string reached pdf.js as a module specifier and resolved against the filesystem root. That
 * mock is gone, along with the `DOMMatrix` and `Uint8Array.toHex` polyfills in `setupTests.ts` and
 * the `mammoth` browser-build alias: every one of them existed to fake a browser for two browser
 * libraries, and none of it survived contact with CI, where the PDF cases hung on every run the
 * repository has ever had.
 *
 * What that buys is not tidiness. `pdfjs-dist` disables the real `Worker` whenever `isNodeJS` is
 * true, so the jsdom version never tested the worker path the app ships — it tested a same-thread
 * fallback that only exists in Node. Here `Worker` is real, `?url` is a real URL, and the parser
 * is the one an admin's browser runs.
 */

/**
 * Browser-side PDF/DOCX extraction (FULLPLAN §33) — the leg the AI generation flow depends on and
 * nothing tested.
 *
 * This matters more than a utility test usually would, because of where it sits: §31 Mode A does
 * the parsing **in the browser** (a free Worker has 10 ms of CPU and a 3 MB bundle, so it can go
 * nowhere else), and the Worker only ever sees `extracted_text`. That means a broken parser here
 * does not look like a broken parser — it looks like "the AI generated nothing from my PDF", a
 * server-side symptom for a client-side cause. The server cannot detect it and the server's logs
 * cannot show it.
 *
 * The fixtures are built in-process rather than committed as binaries: a checked-in .docx is a
 * blob no reviewer can read in a diff, and the DOCX case in particular is *exactly* the zip
 * structure mammoth looks for, spelled out.
 */

/** A minimal but genuinely valid .docx: a zip whose `word/document.xml` holds the paragraphs. */
async function docxFile(paragraphs: string[], name = 'handbook.docx'): Promise<File> {
  const zip = new JSZip();

  zip.file(
    '[Content_Types].xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`,
  );

  zip.file(
    '_rels/.rels',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`,
  );

  zip.file(
    'word/document.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${paragraphs.map((text) => `<w:p><w:r><w:t>${text}</w:t></w:r></w:p>`).join('\n    ')}
  </w:body>
</w:document>`,
  );

  const blob = await zip.generateAsync({ type: 'arraybuffer' });

  return new File([blob], name, {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  });
}

/**
 * A minimal but genuinely valid PDF with a real text layer, written by hand.
 *
 * Uncompressed and with a correct xref table, because pdf.js validates both. Writing the bytes out
 * is the point: this is the shape of file a counselor uploads, and a fixture generated by the same
 * library that reads it would prove nothing.
 */
function pdfFile(lines: string[], name = 'handbook.pdf'): File {
  const content = [
    'BT',
    '/F1 12 Tf',
    '72 720 Td',
    ...lines.flatMap((line) => [`(${line.replace(/([()\\])/g, '\\$1')}) Tj`, '0 -18 Td']),
    'ET',
  ].join('\n');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];

  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = pdf.length;

  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  // latin1: every byte written above is a single code unit, and a UTF-8 encode would silently
  // shift every xref offset the parser is about to check.
  const bytes = Uint8Array.from(pdf, (character) => character.charCodeAt(0) & 0xff);

  return new File([bytes], name, { type: 'application/pdf' });
}

describe('DOCX extraction (§33)', () => {
  it('pulls the document text out of a real .docx package', async () => {
    const file = await docxFile([
      'Effective study habits begin with a consistent weekly schedule.',
      'Students who review notes within a day retain substantially more.',
    ]);

    const text = await extractText(file);

    expect(text).toContain('consistent weekly schedule');
    expect(text).toContain('review notes within a day');
  });

  it('is case-insensitive about the extension — a .DOCX is still a DOCX', async () => {
    const file = await docxFile(['Uppercase extensions come off real machines.'], 'HANDBOOK.DOCX');

    await expect(extractText(file)).resolves.toContain('Uppercase extensions');
  });

  it('refuses a document with no text rather than sending an empty prompt to the model', async () => {
    await expect(extractText(await docxFile([]))).rejects.toBeInstanceOf(ExtractionError);
  });
});

describe('PDF extraction (§33)', () => {
  it('pulls the text layer out of a real PDF', async () => {
    const text = await extractText(
      pdfFile([
        'Time management is the foundation of academic success.',
        'Focus is trainable and improves with deliberate practice.',
      ]),
    );

    expect(text).toContain('Time management is the foundation');
    expect(text).toContain('Focus is trainable');
  });

  it('names the scanned-document case, which is the one users actually hit', async () => {
    // A valid PDF with no text-drawing operators at all — what a photocopier produces.
    await expect(extractText(pdfFile([]))).rejects.toThrow(/no text layer/i);
  });
});

describe('the guards around both', () => {
  it('rejects a file type neither parser handles', async () => {
    const file = new File(['plain text is not a supported upload'], 'notes.txt', {
      type: 'text/plain',
    });

    await expect(extractText(file)).rejects.toThrow(/Only PDF and DOCX/i);
  });

  it('enforces the §34 cap in the browser, before half a megabyte is uploaded for a 422', async () => {
    const oversized = await docxFile(['x'.repeat(MAX_EXTRACTED_TEXT_CHARS + 1_000)]);

    await expect(extractText(oversized)).rejects.toThrow(/exceeds the/i);
  });
});
